name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

      - name: Commit and push metrics
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metrics.base.svg
          git commit -m "chore: update metrics"
          git push
