name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # Tous les jours à minuit
  workflow_dispatch:              # Lancer manuellement

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
